name: NoiseMap
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - expat=2.5.0
  - freetype=2.12.1
  - intel-openmp=2023.1.0
  - jpeg=9e
  - lerc=3.0
  - libdeflate=1.17
  - libexpat=2.5.0
  - libffi=3.4.4
  - libpng=1.6.39
  - libsqlite=3.45.1
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - noise=1.2.2
  - numpy=1.26.3
  - numpy-base=1.26.3
  - openjpeg=2.4.0
  - openssl=3.2.1
  - pillow=10.2.0
  - pip=23.3.1
  - python=3.12.2
  - python_abi=3.12
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tk=8.6.13
  - tzdata=2023d
  - ucrt=10.0.20348.0
  - vc=14.2
  - vc14_runtime=14.38.33130
  - vs2015_runtime=14.38.33130
  - wheel=0.41.2
  - xz=5.4.5
  - zlib=1.2.13
  - zstd=1.5.5
